# Generated by Django 3.2.7 on 2021-09-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_addmovies_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmovies',
            name='movies_discription',
        ),
        migrations.CreateModel(
            name='moviescounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Counter', models.IntegerField()),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.addmovies')),
            ],
        ),
    ]
