# Generated by Django 3.2.7 on 2021-09-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_auto_20210910_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmovies',
            name='link_title',
            field=models.TextField(default='Episode'),
        ),
        migrations.AlterField(
            model_name='addmovies',
            name='link',
            field=models.TextField(default='Link'),
        ),
        migrations.AlterField(
            model_name='addmovies',
            name='movies_intro',
            field=models.TextField(default='Best Movies'),
        ),
    ]
