# Generated by Django 3.2.7 on 2021-09-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_addmovies_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmovies',
            old_name='category_type',
            new_name='category_types',
        ),
    ]
