# Generated by Django 3.2.7 on 2021-09-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_auto_20210910_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviescounter',
            name='Counter',
            field=models.IntegerField(default=0),
        ),
    ]
