# Generated by Django 3.2.7 on 2021-09-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_auto_20210911_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='movieslink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviesname', models.CharField(max_length=25)),
                ('link_title', models.TextField(default='Episode')),
                ('link', models.TextField(default='Link')),
            ],
        ),
        migrations.RemoveField(
            model_name='addmovies',
            name='link',
        ),
        migrations.RemoveField(
            model_name='addmovies',
            name='link_title',
        ),
    ]
