# Generated by Django 3.2.7 on 2021-09-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_auto_20210911_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieslink',
            name='moviesname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.addmovies'),
        ),
    ]
